### ISSUE TITLE
OSError: Can't load config for 'prithivida/parrot_adequacy_on_BART'. Make sure that....

### ISSUE THREAD

**Issue by katreparitosh** [PrithivirajDamodaran/Styleformer#1]
Hi Prithviraj,

Fantastic work you are doing. 

While testing your models, I intended to deploy the model wrapped in a flask app on EC2.

Although the results work on Google Colab, I receive the following error on EC2 - 

```
OSError: Can't load config for 'prithivida/parrot_adequacy_on_BART'. Make sure that:

- 'prithivida/parrot_adequacy_on_BART' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'prithivida/parrot_adequacy_on_BART' is the correct path to a directory containing a config.json file
```

Can you guide me on how this can be resolved?

Regards,
Paritosh

**Comment by PrithivirajDamodaran** [comment]
This is due to the fact HF has recently moved all models behind SSL. So you must be behind a firewall. Hence the issue. 

I suggest try using styleformer in Colab and see mostly it should work, you won't face this issue.

**Comment by katreparitosh** [comment]
Okay, got it. 

In that case, I'll have to disable the firewall on my EC2 instance?
