### ISSUE TITLE
Single model with multiple task prefixes

### ISSUE THREAD

**Issue by chrsbats** [PrithivirajDamodaran/Styleformer#20]
Just a quick question.  

Given that Styleformer is based on the T5 model is it possible to have a single model that uses 4 different task prefixes as an option?  Or would that require using a larger model than t5-base to maintain the same level of accuracy?

**Comment by PrithivirajDamodaran** [comment]
Theoretically yes,
But practically A2P and P2A for instance was trained on a T5-small. So one need not load a base or large model for A2P / P2A. That said we could consolidate the tasks at multiple levels just A2P and P2A together could be one model or all tasks could one model. These are a matter of choice dictated by practicality and number of training samples/task.
