### ISSUE TITLE
Issue with loading saved models

### ISSUE THREAD

**Issue by Naviden** [PrithivirajDamodaran/Styleformer#6]
Hi,
I'm trying to save and load the tokenizer and model.
I use the following to save them:
```
tokenizer = AutoTokenizer.from_pretrained("prithivida/informal_to_formal_styletransfer")
tokenizer.save_pretrained('./data/style_tokenizer')
model = AutoModelForSeq2SeqLM.from_pretrained("prithivida/informal_to_formal_styletransfer")
model.save_pretrained('./data/style_model')
```

But when I try to load them, from the local path, I get the following error:
```
OSError: Can't load config for '../data/style_tokenizer'. Make sure that:

- '../data/style_tokenizer' is a correct model identifier listed on 'https://huggingface.co/models'

- or '../data/style_tokenizer' is the correct path to a directory containing a config.json file
```

This somehow makes sense since saving the vectorizer, no config.json is being created.

Any idea how can I save/load the tokenizer and model?

**Comment by PrithivirajDamodaran** [comment]
Refer to [bug 1](https://github.com/PrithivirajDamodaran/Styleformer/issues/1)

It's better to check if there are any similar closed bugs before opening one.
