### ISSUE TITLE
Trimming long sentences

### ISSUE THREAD

**Issue by Nomiluks** [PrithivirajDamodaran/Styleformer#7]
Following the code snippet for a better understanding of the problem, I am facing. 

```
from styleformer import Styleformer
import torch
import warnings
warnings.filterwarnings("ignore")

# style = [0=Casual to Formal, 1=Formal to Casual, 2=Active to Passive, 3=Passive to Active etc..]
sf = Styleformer(style = 0) 

source_sentences = [
                   "Corruption in african countries hinders economic, political and social development. It is a major obstacle to economic growth, good governance and fundamental freedoms, such as freedom of speech or the right of citizens to hold governments accountable. In addition, corruption affects the lives of individuals, families and communities. The 10th global corruption barometer (gcb) program - in africa, shows that while many people in africa feel that corruption is on the rise in their country, many also feel confident that, as citizens, they can make a difference in the fight against corruption."
]

for paragraph in source_sentences:
    # sentences = sent_tokenize(paragraph)
    sentences = paragraph.split('. ')
    for source_sentence in sentences:
        target_sentence = sf.transfer(source_sentence)
        print("-" *100)
        print("[Casual] ", source_sentence)
        print("-" *100)
        if target_sentence is not None:
            print("[Formal] ",target_sentence)
            print()
        else:
            print("No good quality transfers available !")
```
Program Output

> ----------------------------------------------------------------------------------------------------
> [Casual]  Corruption in african countries hinders economic, political and social development
> ----------------------------------------------------------------------------------------------------
> [Formal]  In African countries, corruption affects economic, political, and social development.
> 
> ----------------------------------------------------------------------------------------------------
> [Casual]  It is a major obstacle to economic growth, good governance and fundamental freedoms, such as freedom of speech or the right of citizens to hold governments accountable
> ----------------------------------------------------------------------------------------------------
> [Formal]  It's a major obstacle to economic growth, good governance, and fundamental freedoms, such as the freedom of speech or the right of citizens to
> 
> ----------------------------------------------------------------------------------------------------
> [Casual]  In addition, corruption affects the lives of individuals, families and communities
> ----------------------------------------------------------------------------------------------------
> [Formal]  Additionally, corruption has a negative impact on individuals, families and communities.
> 
> ----------------------------------------------------------------------------------------------------
> [Casual]  The 10th global corruption barometer (gcb) program - in africa, shows that while many people in africa feel that corruption is on the rise in their country, many also feel confident that, as citizens, they can make a difference in the fight against corruption.
> ----------------------------------------------------------------------------------------------------
> [Formal]  The tenth Global Corruptibility Barometer (GCB) program - in Africa - shows that while many people in Africa feel that corruption
> 

Please help to fix this for longer sentences. Thanks in advance!

**Comment by PrithivirajDamodaran** [comment]
This is by design, actually the model is trained ONLY on 32 lengths sentences. No plans for now to train on longer sentences. May be in the future, but sorry can't promise.

I am not sure if this will help, In the mean time why don't you try sentence segmentation using spacy or some custom logic and feed the model with shorter sentences ?

**Comment by Nomiluks** [comment]
okay, is there any hack i can use your model?

**Comment by PrithivirajDamodaran** [comment]
Updated the answer :)

**Comment by Nomiluks** [comment]
> This is by design, actually the model is trained ONLY on 32 lengths sentences. No plans for now to train on longer sentences. May be in the future, but sorry can't promise.
> 
> I am not sure if this will help, In the mean time why don't you try sentence segmentation using spacy or some custom logic and feed the model with shorter sentences ?

32 lengths words or characters @PrithivirajDamodaran
